{
 "title": "Mongo - Springfield",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "interval", "query": "1m,10m,30m,1h,6h,12h,1d,7d" }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "content": "# Mongo Springfield " },
  { "title": "rs-Prod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Document Operations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_metrics_document_total{app_name=\"prom-mongoexporter-prod\"}[$interval])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Query Operations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_op_counters_total{app_name=\"prom-mongoexporter-prod\"}[$interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Replica Query Operations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_op_counters_repl_total{app_name=\"prom-mongoexporter-prod\"}[$interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "10.192.68.82",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mongodb_replset_member_state{name=\"10.192.68.82:37017\", set=\"rs-prod\"}"
    }
   ]
  },
  {
   "title": "10.192.68.83",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mongodb_replset_member_state{name=\"10.192.68.83:37017\", set=\"rs-prod\"}"
    }
   ]
  },
  {
   "title": "10.192.68.84",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mongodb_replset_member_state{name=\"10.192.68.84:37017\", set=\"rs-prod\"}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 9, "y": 7 },
   "yaxes": [
    { "format": "decmbytes", "label": "MB" }
   ],
   "targets": [
    {
     "expr": "mongodb_memory{app_name=\"prom-mongoexporter-prod\",type=~\"resident|virtual\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_network_bytes_total{app_name=\"prom-mongoexporter-prod\"}[$interval])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "rs-Stage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Document Operations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_metrics_document_total{app_name=\"prom-mongoexporter-stage\"}[$interval])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Query Operations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 13 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_op_counters_total{app_name=\"prom-mongoexporter-stage\"}[$interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Replica Query Operations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 13 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_op_counters_repl_total{app_name=\"prom-mongoexporter-stage\"}[$interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "10.192.68.82",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mongodb_replset_member_state{name=\"10.192.68.82:57017\", set=\"rs-stage\"}"
    }
   ]
  },
  {
   "title": "10.192.68.83",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mongodb_replset_member_state{name=\"10.192.68.83:57017\", set=\"rs-stage\"}"
    }
   ]
  },
  {
   "title": "10.192.68.84",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mongodb_replset_member_state{name=\"10.192.68.84:57017\", set=\"rs-stage\"}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 9, "y": 19 },
   "yaxes": [
    { "format": "decmbytes", "label": "MB" }
   ],
   "targets": [
    {
     "expr": "mongodb_memory{app_name=\"prom-mongoexporter-stage\",type=~\"resident|virtual\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 19 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_network_bytes_total{app_name=\"prom-mongoexporter-stage\"}[$interval])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "rs-Dev", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Document Operations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_metrics_document_total{app_name=\"prom-mongoexporter-dev\"}[$interval])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Query Operations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 25 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_op_counters_total{app_name=\"prom-mongoexporter-dev\"}[$interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Replica Query Operations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 25 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_op_counters_repl_total{app_name=\"prom-mongoexporter-dev\"}[$interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "10.192.68.82",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 31 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mongodb_replset_member_state{name=\"10.192.68.82:47017\", set=\"rs-dev\"}"
    }
   ]
  },
  {
   "title": "10.192.68.83",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 31 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mongodb_replset_member_state{name=\"10.192.68.83:47017\", set=\"rs-dev\"}"
    }
   ]
  },
  {
   "title": "10.192.68.84",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 31 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mongodb_replset_member_state{name=\"10.192.68.84:47017\", set=\"rs-dev\"}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 9, "y": 31 },
   "yaxes": [
    { "format": "decmbytes", "label": "MB" }
   ],
   "targets": [
    {
     "expr": "mongodb_memory{app_name=\"prom-mongoexporter-stage\",type=~\"resident|virtual\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 31 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_network_bytes_total{app_name=\"prom-mongoexporter-dev\"}[$interval])",
     "legendFormat": "{{state}}"
    }
   ]
  }
 ]
}