{
 "title": "Status",
 "description": "Monitor Up/Down Status Set In Prometheus",
 "tags": [
  "alerts",
  "linux",
  "windows"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "node",
    "query": "label_values(probe_success{job=\"ping\"}, instance) "
   }
  ]
 },
 "panels": [
  { "title": "HTTP STATUS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Microsite HTTP Status", "type": "text", "gridPos": { "h": 1, "w": 10, "x": 0, "y": 1 } },
  { "title": "API HTTP Status", "type": "text", "gridPos": { "h": 1, "w": 10, "x": 14, "y": 1 } },
  {
   "title": "PPS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=~\"https://buy.something.com/pps/\"}"
    }
   ]
  },
  {
   "title": "Demo",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=~\"https://buy.something.com/demo/\"}"
    }
   ]
  },
  {
   "title": "Motionsoft",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=~\"https://buy.something.com/motionsoft/\"}"
    }
   ]
  },
  {
   "title": "Dev - nonCoreDev",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{job=\"blackbox\", instance=~\"https://dev-api.something.com:30011/vitality/report\"}"
    }
   ]
  },
  {
   "title": "Internal Sandbox - nonCoreDev",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{job=\"blackbox\", instance=~\"https://internal-sandbox.something.com/vitality/report\"}"
    }
   ]
  },
  {
   "title": "Internal API - nonCoreDev",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{job=\"blackbox\", instance=~\"https://internal-api.something.com/vitality/report\"}"
    }
   ]
  },
  {
   "title": "Cardflight",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 5 },
   "repeat": "node",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=~\"https://buy.something.com/cardflight/\"}"
    }
   ]
  },
  {
   "title": "Promerchant",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=~\"https://buy.something.com/promerchant/\"}"
    }
   ]
  },
  {
   "title": "Shift4",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 5 },
   "repeat": "node",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{job=\"blackbox\", instance=~\"https://buy.something.com/shift4/\"}"
    }
   ]
  },
  {
   "title": "Dev - CoreDev",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{job=\"blackbox\", instance=~\"https://dev-api.something.com/vitality/report\"}"
    }
   ]
  },
  {
   "title": "Sandbox - CoreDev",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=~\"https://sandbox.something.com/vitality/report\"}"
    }
   ]
  },
  {
   "title": "API - CoreDev",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{job=\"blackbox\", instance=~\"https://api.something.com/vitality/report\"}"
    }
   ]
  },
  { "title": "CoreDev Microservices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "K8 Microservices",
   "type": "table",
   "description": "Http status codes from blackbox exporter",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "up{kubernetes_namespace=~\".+[coreDev-staging | coreDev-production]\"}"
    }
   ]
  }
 ]
}