# ------------------- Prometheus Blackbox - Service for Development ------------------- #
apiVersion: v1
kind: Service
metadata:
  name: blackbox-service
  namespace: dev-things  
spec:
  selector: 
    app: blackbox-exporter
  type: NodePort  
  ports:
    - port: 9115
      targetPort: 9115 
      nodePort: 30001

---
# ------------------- Deployment ------------------- #
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: blackbox-deployment
  namespace: dev-things
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: blackbox-exporter
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path:   /metrics
        prometheus.io/port:   '9115'
    spec:
      containers:
        - name: prometheus-blackbox
          image: prom/blackbox-exporter:v0.12.0 
          ports: 
            - containerPort: 9115
      imagePullSecrets:
        - name: regcred