# ------------------- MongoExporter - Service for Development ------------------- #
apiVersion: v1
kind: Service
metadata:
  name: mongoexporter-prod-service
  namespace: dev-things
spec:
  selector: 
    app: prom-mongoexporter-prod
  type: NodePort  
  ports:
    - port: 9001
      targetPort: 9001 
      nodePort: 30005
---
# ------------------- Deployment ------------------- #
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongoexporter-deployment
  namespace: dev-things
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: prom-mongoexporter-prod
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path:   /metrics
    spec:
      containers:
        - name: prome-mongoexporter-prod
          image: registry.something/mongoexporter:latest
          ports:
            - containerPort: 9001
          env:
          - name: MONGODB_URL
            value: "mongodb://10.192.60.1:37017,10.192.60.2:37017,10.192.60.3:37017/?replicaSet=rs-prod"
      imagePullSecrets:
        - name: regcred  
