groups:
  - name: example
    rules:
    - alert: InstanceDown
      expr: up == 0 
      for: 1m
      labels: 
        severity: page
      annotations: 
        summary: "Instance {{ $labels.instance}} down"
        description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than a minute."
    - alert: EndpointDown
      expr: probe_success == 0
      for: 150s
      labels: 
        severity: critical
      annotations: 
        summary: "Endpoint {{ $labels.instance }} down"